// DATABASE OF SENTENCES BY CATEGORIES (HEALTH, LOVE, WORK and MONEY)

// Sentences health
const health = [
"A small change in routine will boost your wellbeing.",
"Focus on mental as well as physical wellbeing.",
"Take time to rest and recover.",
"You will feel energized today.",
"Exercise will bring positive results.",
"Stay hydrated and mindful of your diet.",
"Listen to your body and avoid overexertion.",
"A minor issue may arise but it will pass quickly.",
"Balance is key to maintaining your health.",
"Stress could affect you so try to relax.",
"Fresh air will clear your mind.",
"Healthy habits will feel easier today.",
"Your body will respond well to care.",
"Stretching will improve your mood.",
"You may discover a new wellness routine.",
"Consistency will bring noticeable improvements.",
"Your immune system will feel stronger.",
"Rest will be more beneficial than usual.",
"Mindfulness will help reduce tension.",
"You will feel motivated to make healthier choices.",
"Your energy levels will stabilize.",
"A calm environment will support your wellbeing.",
"You may feel the need to slow down.",
"Good sleep will enhance your clarity.",
"You will feel more in tune with your body.",
"A positive mindset will boost your health.",
"Gentle movement will help you feel grounded.",
"You may overcome a lingering discomfort.",
"Your resilience will be higher today.",
"Breathing exercises will help you refocus.",
"You will feel encouraged to break a bad habit.",
"Your body will appreciate a lighter routine.",
"You may feel unusually refreshed.",
"Healthy boundaries will protect your wellbeing.",
"You will find comfort in simple rituals.",
"Your stamina will gradually increase.",
"You may feel inspired to try a new sport.",
"Your mood will benefit from physical activity.",
"You will feel more balanced emotionally.",
"Small improvements will feel significant.",
"You may feel relief from recent tension.",
"Your focus will improve with proper rest.",
"You will feel more aligned with your goals.",
"Your body will respond well to nourishment.",
"You may feel compelled to detox your routine.",
"You will find strength in slowing down.",
"Your wellbeing will benefit from gratitude.",
"You may feel a renewed sense of vitality.",
"Your health will improve through patience."
];

// Sentences love
const love = [
"Be open about your feelings.",
"A past connection may reappear.",
"Love will grow with patience.",
"Communication will strengthen your relationship.",
"Take time to understand your partner.",
"Enjoy the small moments together.",
"A romantic surprise may come your way.",
"Trust is essential today.",
"New connections are on the horizon.",
"A misunderstanding could arise so stay calm.",
"You may feel a spark with someone unexpected.",
"Honesty will deepen your bond.",
"You will feel appreciated by someone close.",
"A heartfelt conversation will bring clarity.",
"You may reconnect with someone meaningful.",
"Affection will feel more natural today.",
"Your intuition will guide your love life.",
"You will feel more confident expressing emotions.",
"A tender moment will brighten your day.",
"You may attract someone with similar values.",
"Patience will bring emotional harmony.",
"You will feel more connected than usual.",
"A romantic opportunity may surprise you.",
"You may resolve a lingering tension.",
"Your charm will be especially strong today.",
"You will feel supported by someone you care about.",
"A new phase in love may begin.",
"You may feel drawn to someone with authenticity.",
"Your heart will feel lighter today.",
"You will find comfort in vulnerability.",
"A meaningful gesture will touch you.",
"You may discover a shared passion.",
"Your relationship will feel more balanced.",
"You will feel inspired to show affection.",
"A moment of clarity will guide your choices.",
"You may attract positive attention.",
"Your emotional needs will feel clearer.",
"You will feel more open to connection.",
"A romantic idea may take shape.",
"You may feel unexpectedly adored.",
"Your love life will feel more hopeful.",
"You will feel encouraged to take a chance.",
"A deep conversation will strengthen trust.",
"You may feel closer to someone than before.",
"Your heart will feel more grounded.",
"You will appreciate someone with sincerity.",
"A new dynamic may emerge in your love life.",
"You may feel ready for a new beginning.",
"Your emotions will feel easier to express.",
"You will feel warmth from someone special."
];

// Sentences work
const work = [
"Opportunities for growth will appear.",
"Innovation will bring rewards.",
"Stay focused on your goals.",
"Your efforts will be recognized.",
"A challenge will test your skills.",
"Patience will help you succeed.",
"Avoid distractions to stay productive.",
"Be cautious with decisions today.",
"Teamwork will lead to success.",
"A new project may begin.",
"Your creativity will shine at work.",
"You may receive helpful feedback.",
"Your leadership will be appreciated.",
"You will feel motivated to improve.",
"An idea you have will gain support.",
"You may learn a valuable skill.",
"Your productivity will increase.",
"You will feel more organized today.",
"Collaboration will bring strong results.",
"You may impress someone influential.",
"Your confidence will grow at work.",
"You will find clarity in a complex task.",
"You may resolve a work related issue.",
"Your dedication will pay off.",
"You will feel inspired to innovate.",
"You may discover a new opportunity.",
"Your communication will be effective.",
"You will feel more in control of your tasks.",
"A breakthrough may occur unexpectedly.",
"You may feel proud of your progress.",
"Your work environment will feel supportive.",
"You will handle pressure with ease.",
"You may receive recognition for your ideas.",
"Your focus will be sharper than usual.",
"You will feel encouraged to take initiative.",
"A productive rhythm will emerge.",
"You may find a smarter way to work.",
"Your skills will feel more refined.",
"You will feel aligned with your goals.",
"A positive shift may occur at work.",
"You may feel motivated to reorganize.",
"Your determination will stand out.",
"You will adapt well to a new challenge.",
"You may feel inspired by a colleague.",
"Your work ethic will shine today.",
"You will feel more balanced professionally.",
"You may receive unexpected support.",
"Your ideas will resonate with others.",
"You will feel ready for the next step."
];

// Sentences money
const money = [
"Think long term about finances.",
"Unexpected expenses may arise.",
"Opportunities to earn more will appear.",
"Avoid unnecessary spending.",
"Savings will bring peace of mind.",
"Financial gains are possible.",
"Plan your budget carefully.",
"Seek advice before major decisions.",
"A smart investment could pay off.",
"Be cautious with large purchases.",
"You may find a new way to save.",
"Your financial discipline will pay off.",
"You will feel more secure about money.",
"A small expense may bring big value.",
"You may receive helpful financial guidance.",
"Your income may increase soon.",
"You will feel motivated to organize finances.",
"A financial opportunity may surprise you.",
"You may recover from a recent setback.",
"Your budgeting skills will improve.",
"You will feel more confident about spending.",
"A wise choice will benefit your future.",
"You may discover a new income source.",
"Your savings will grow steadily.",
"You will feel encouraged to invest.",
"A financial concern will ease.",
"You may negotiate successfully.",
"Your financial awareness will sharpen.",
"You will feel more in control of expenses.",
"A profitable idea may emerge.",
"You may avoid a costly mistake.",
"Your money habits will improve.",
"You will feel optimistic about finances.",
"A delayed payment may finally arrive.",
"You may receive a small reward.",
"Your financial intuition will be strong.",
"You will feel inspired to plan ahead.",
"A stable period is approaching.",
"You may find value in simplicity.",
"Your financial goals will feel achievable.",
"You will feel empowered to make changes.",
"A smart purchase will benefit you.",
"You may gain clarity about priorities.",
"Your resources will stretch further.",
"You will feel more responsible with money.",
"A financial door may open.",
"You may receive unexpected support.",
"Your patience will bring financial stability.",
"You will feel ready to improve your finances."
];


// PICKING A SENTENCE OF EACH CATEGORY AND CREATING OBJECT sentences WITH THE 4 PICKED SENTENCES

// Random indexes of each sentences array
const random_health = Math.floor(Math.random() * health.length);
const random_love = Math.floor(Math.random() * love.length);
const random_work = Math.floor(Math.random() * work.length);
const random_money = Math.floor(Math.random() * money.length);

// Resulting picked random sentences
const random_sentence_health = health[random_health];
const random_sentence_love = love[random_love];
const random_sentence_work = work[random_work];
const random_sentence_money = money[random_money];

// Creation of the sentences object with the 4 randomly picked sentences
const sentences = {
  random_sentence_health,
  random_sentence_love,
  random_sentence_work,
  random_sentence_money
};

console.log(sentences);

// EXPORTING OBJECT sentences
export default sentences;